[build]
  base = "client/"
  command = "npm run build"
  publish = "client/build"

[[redirects]]
  from = "/api/*"
  to = "http://192.168.9.124:3001/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
